/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PlayerTest {
    @Test
    void test01() {
        assertTrue(true);
    }
}
